########################################################################################
########################################################################################
### Influenza Aerosol PFU/RNA Data Analysis - Several Viruses
### experimental data generated by Joanna Pulit-Penaloza
### primary analyses and plots
### 30 April 2025 - 12 November 2025
### Troy J. Kieran
########################################################################################
########################################################################################
### Load packages
library(tidyverse)
library(tidylog)
library(patchwork)

########################################################################################
### Import Data

norm_data <- read.csv("Source_Data/FullData.csv", header = TRUE, check.names = FALSE)
## drop added row number column
norm_data <- norm_data[, -1]

## rename viruses to add the /
norm_data$Virus <- str_replace_all(norm_data$Virus, "(\\D)(\\d)", "\\1/\\2")
norm_data$Virus <- ifelse(norm_data$Virus == "BC", "BC/PHL", norm_data$Virus)

## set Sample & Virus levels
norm_data$Sample <- factor(norm_data$Sample, levels = c("NW", "NIOSH", "SPOT"))
norm_data$Virus <- factor(norm_data$Virus, 
                          levels = c("NE/14", "AL/39", "Anhui/1", "MI/90", "CO/137", 
                                     "CA/147", "BC/PHL", "WA/239", "VN/1203"))

########################################################################################

## rename labels for plots
virus_sample_labels <- as_labeller(c(
  "BC/PHL" = "BC/PHL",
  "CA/147" = "CA/147",
  "CO/137" = "CO/137",
  "AL/39" = "AL/39",
  "Anhui/1" = "Anhui/1",
  "MI/90" = "MI/90",
  "NE/14" = "NE/14",
  "VN/1203" = "VN/1203",
  "WA/239" = "WA/239",
  "NW" = "Nasal Wash (NW)",
  "NIOSH" = "Air / BC 251",
  "SPOT" = "Air / SPOT",
  "d1" = "d1", "d2" = "d2", "d3" = "d3", "d5" = "d5",
  "PFU" = "PFU", "RNA" = "RNA", "ratio" = "Ratio (RNA/PFU)",
  "High-transmissible" = "High-transmissible", 
  "Low-transmissible" = "Low-transmissible", 
  "Non-transmissible" = "Non-transmissible",
  "non-transmissible" = "Non-transmissible",
  "transmissible" = "Transmissible"))

## adjustments for particular plots
virus_sample_labels2 <- as_labeller(c(
  "BC/PHL" = "BC/PHL",
  "CA/147" = "CA/147",
  "CO/137" = "CO/137",
  "AL/39" = "AL/39",
  "Anhui/1" = "Anhui/1",
  "MI/90" = "MI/90",
  "NE/14" = "NE/14",
  "VN/1203" = "VN/1203",
  "WA/239" = "WA/239",
  "NW" = "Nasal Wash (NW)",
  "NIOSH" = "Air / BC 251",
  "SPOT" = "Air / SPOT",
  "d1" = "d1", "d2" = "d2", "d3" = "d3", "d5" = "d5",
  "PFU" = "Infectious Virus", "RNA" = "Viral RNA", "ratio" = "Ratio (RNA/PFU)",
  "High-transmissible" = "High-transmissible", 
  "Low-transmissible" = "Low-transmissible", 
  "Non-transmissible" = "Non-transmissible",
  "non-transmissible" = "Non-transmissible",
  "transmissible" = "Transmissible"))

########################################################################################
########################################################################################

### Overall summary stats

norm_data %>% 
  #filter(Sample != 'NW') %>%
  group_by(Sample) %>%
  summarise(mean_RNA = mean(RNA, na.rm = TRUE),
            ci_lower_RNA = mean(RNA, na.rm = TRUE) - 1.96 * sd(RNA, na.rm = TRUE) / sqrt(n()),
            ci_upper_RNA = mean(RNA, na.rm = TRUE) + 1.96 * sd(RNA, na.rm = TRUE) / sqrt(n()),
            mean_PFU = mean(PFU, na.rm = TRUE),
            ci_lower_PFU = mean(PFU, na.rm = TRUE) - 1.96 * sd(PFU, na.rm = TRUE) / sqrt(n()),
            ci_upper_PFU = mean(PFU, na.rm = TRUE) + 1.96 * sd(PFU, na.rm = TRUE) / sqrt(n()),
            mean_ratio = mean(ratio, na.rm = TRUE),
            ci_lower_ratio = mean(ratio, na.rm = TRUE) - 1.96 * sd(ratio, na.rm = TRUE) / sqrt(n()),
            ci_upper_ratio = mean(ratio, na.rm = TRUE) + 1.96 * sd(ratio, na.rm = TRUE) / sqrt(n()),
            ## medians
            median_RNA = median(RNA, na.rm = TRUE),
            median_PFU = median(PFU, na.rm = TRUE),
            median_ratio = median(ratio, na.rm = TRUE)) %>% View()

## ratio with out zero values
norm_data %>% 
  #filter(Sample != 'NW') %>%
  filter(ratio > 0) %>%
  group_by(Sample) %>%
  summarise(mean_ratio = mean(ratio, na.rm = TRUE),
            ci_lower_ratio = mean(ratio, na.rm = TRUE) - 1.96 * sd(ratio, na.rm = TRUE) / sqrt(n()),
            ci_upper_ratio = mean(ratio, na.rm = TRUE) + 1.96 * sd(ratio, na.rm = TRUE) / sqrt(n()),
            median_ratio = median(ratio, na.rm = TRUE)) %>% View()

########################################################################################
########################################################################################
### FIGURES ###
########################################################################################
########################################################################################

### FIGURE 1

## Creation of the figure from GraphPad Prisim

########################################################################################

### FIGURE 2

## summarize data for plots & Supplemental Table 2
data_stats <-
  norm_data %>%
  group_by(Virus, day, Sample) %>%
  #mutate(RNA = ifelse(RNA == 0, 1.5, RNA)) %>%
  summarise(Nr = sum(!is.na(RNA)),
            Np = sum(!is.na(PFU)),
            mr = mean(RNA),
            ser = sd(RNA)/sqrt(length(RNA)),
            mp = mean(PFU),
            sep = sd(PFU)/sqrt(length(PFU)),
            sdr = sd(RNA),
            sdp = sd(PFU),
            ## Coefficient of Variation (CV)
            cvr = ((sdr/mr) * 100),
            cvp = ((sdp/mp) * 100),
            ## https://pmc.ncbi.nlm.nih.gov/articles/PMC9196089/
            ## Robust CV Based on Interquartile Range (RCV𝑄)
            rcvqr = ((0.75 * (IQR(RNA)/median(RNA))) * 100),
            rcvqp = ((0.75 * (IQR(PFU)/median(PFU))) * 100),
            ## Robust CV Based on Median Absolute Deviation (RCV𝑀)
            rcvmr = ((1.4826 * (mad(RNA)/median(RNA))) * 100),
            rcvmp = ((1.4826 * (mad(PFU)/median(PFU))) * 100)) %>%
  mutate(VirusGroup = case_when(
    Virus %in% c("NE/14", "AL/39") ~ "High-transmissible",
    Virus %in% c("Anhui/1", "MI/90") ~ "Low-transmissible",
    TRUE ~ "Non-transmissible"))

## set Virus and transmissibility levels/order
data_stats$Virus <- factor(data_stats$Virus, 
                           levels = c("NE/14", "AL/39", "Anhui/1", "MI/90", "CO/137", 
                                      "CA/147", "BC/PHL", "WA/239", "VN/1203"))

data_stats$VirusGroup <- factor(data_stats$VirusGroup,
                                levels = c("High-transmissible", 
                                           "Low-transmissible", 
                                           "Non-transmissible"))

## for adding individual data points
norm_data_reduced <- norm_data %>%
  select(Virus, day, Sample, PFU, RNA) %>%
  mutate(VirusGroup = case_when(
    Virus %in% c("NE/14", "AL/39") ~ "High-transmissible",
    Virus %in% c("Anhui/1", "MI/90") ~ "Low-transmissible",
    TRUE ~ "Non-transmissible"))

## plot PFU & RNA w/ standard error
## Bar (PFU) & Line (RNA) plots
data_stats %>%
  ggplot(aes(x = day, color = Sample, fill = Sample)) +
  geom_bar(aes(y = mp), stat = "identity", alpha = 0.4, 
           position = position_dodge(width = 0.95)) +
  geom_jitter(aes(x = day, y =  PFU, color = Sample, fill = Sample), 
              shape = 17, size = 1.5, data = norm_data_reduced) +
  geom_errorbar(aes(ymin = mp - sep, ymax = mp + sep), 
                width = 0.2, alpha = 0.7, color = "black") +
  geom_ribbon(aes(group = 1, ymin = mr - ser, ymax = mr + ser), 
              fill = "darkslategray4", alpha = 0.2) +
  #geom_point(aes(y = mr), size = 2, alpha = 1) +
  geom_line(aes(y = mr, group = 1), size = 0.8, alpha = 1) +
  geom_jitter(aes(x = day, y =  RNA, color = Sample, fill = Sample), 
              shape = 15, size = 1.5, data = norm_data_reduced) +
  ## have facets for transmissibility & Virus
  ggh4x::facet_nested(rows = vars(Sample), cols = vars(VirusGroup, Virus),
                      labeller = labeller(Sample = virus_sample_labels,
                                          Virus = virus_sample_labels,
                                          VirusGroup = label_value),
                      scales = "free_y", space = "fixed", render_empty = FALSE) +
  scale_fill_viridis_d(end = 0.8, labels = virus_sample_labels) +
  scale_color_viridis_d(end = 0.8, labels = virus_sample_labels) +
  scale_y_continuous(
    name = expression(log[10]~paste("PFU  (bars)")),
    breaks = seq(0, 11, by = 1),
    sec.axis = sec_axis(~., name = expression(log[10]~paste("RNA copies  (lines)")),
                        breaks = seq(0, 11, by = 1))) +
  xlab("Day Post-Inoculation") +
  theme_bw() +
  theme(legend.position = 'bottom', 
        legend.title = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "grey95"),
        axis.title = element_text(face = "bold"),
        axis.text = element_text(face = "bold")) #-> p1

# ragg::agg_tiff(filename = "Figure_2_PFU_RNA_VirusvSample.tiff",
#                width = 9, height = 8, units = 'in', res = 600,
#                scaling = 1, compression = "lzw")
# plot(p1)
# invisible(dev.off())

########################################################################################

### FIGURE 3

## pairwise NIOSH v SPOT by transmission category

## transform data long
data_long <- norm_data %>%
  pivot_longer(
    cols = c(PFU, RNA, ratio, AUC_PFU, AUC_RNA, ratio_auc),
    names_to = "Variable",
    values_to = "Value")

## calculate means
data_means <- data_long %>%
  filter(Sample != 'NW') %>%
  group_by(Sample, Variable, trans_3cat) %>%
  summarise(mean_value = mean(Value, na.rm = TRUE)) 

data_means_ratio <- data_long %>%
  filter(Sample != 'NW') %>%
  filter(Variable == 'ratio', Value > 0) %>%
  group_by(Sample, Variable, trans_3cat) %>%
  summarise(mean_value = mean(Value, na.rm = TRUE)) 

## plot

data_long %>%
  filter(Sample != 'NW') %>%
  filter(Value > 0) %>% 
  subset(Variable %in% 'ratio') %>%
  distinct() %>%
  ggplot(aes(x = Sample, y = Value, fill = Sample, color = Sample)) +
  geom_jitter(alpha = 0.8, width = 0.25) +
  geom_boxplot(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.2) +
  geom_point(data = data_means_ratio, aes(y = mean_value), 
             color = 'red3', size = 3, show.legend = FALSE) +
  facet_grid(Variable ~ trans_3cat,scales = "free_y", labeller = virus_sample_labels) +
  ggpubr::stat_compare_means(comparisons = list(c("NIOSH", "SPOT")),
                             size = 4, method = 'wilcox.test', label = 'p.format') +
  labs(y = expression("log"[10]*" (RNA copies / PFU)")) +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.position = 'bottom',
        legend.title = element_blank(), 
        panel.grid = element_blank(),
        strip.background = element_rect(fill = "grey95")) +
  scale_y_continuous(breaks = seq(1, 7, by = 1),
                     expand = c(0, 0.5)) +
  scale_fill_viridis_d(begin = 0.4, end = 0.7, labels = virus_sample_labels) +
  scale_color_viridis_d(begin = 0.4, end = 0.7, labels = virus_sample_labels) #-> plot_trans_ratio

data_long %>%
  filter(Sample != 'NW') %>%
  subset(Variable %in% 'RNA') %>%
  distinct() %>%
  ggplot(aes(x = Sample, y = Value, fill = Sample, color = Sample)) +
  geom_jitter(alpha = 0.8, width = 0.25) +
  geom_boxplot(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.2) +
  geom_point(data = data_means %>% filter(Variable == "RNA"), aes(y = mean_value), 
             color = 'red3', size = 3, show.legend = FALSE) +
  facet_grid(Variable ~ trans_3cat,scales = "free_y", labeller = virus_sample_labels2) +
  ggpubr::stat_compare_means(comparisons = list(c("NIOSH", "SPOT")),
                             size = 4, method = 'wilcox.test', label = 'p.format') +
  labs(y = expression("log"[10]*" RNA copies")) +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(), 
        panel.grid = element_blank(),
        strip.background = element_rect(fill = "grey95")) +
  scale_y_continuous(breaks = seq(0, 8, by = 1),
                     expand = c(0, 0.9)) +
  scale_fill_viridis_d(begin = 0.4, end = 0.7, labels = virus_sample_labels) +
  scale_color_viridis_d(begin = 0.4, end = 0.7, labels = virus_sample_labels) #-> plot_trans_rna

data_long %>%
  filter(Sample != 'NW') %>%
  subset(Variable %in% 'PFU') %>%
  distinct() %>%
  ggplot(aes(x = Sample, y = Value, fill = Sample, color = Sample)) +
  geom_jitter(alpha = 0.8, width = 0.25) +
  geom_boxplot(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.2) +
  geom_point(data = data_means %>% filter(Variable == "PFU"), aes(y = mean_value), 
             color = 'red3', size = 3, show.legend = FALSE) +
  facet_grid(Variable ~ trans_3cat, scales = "free_y", labeller = virus_sample_labels2) +
  ggpubr::stat_compare_means(comparisons = list(c("NIOSH", "SPOT")),
                             size = 4, method = 'wilcox.test', label = 'p.format') +
  labs(y = expression("log"[10]*" PFU")) +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(), 
        panel.grid = element_blank(),
        strip.background = element_rect(fill = "grey95")) +
  scale_y_continuous(breaks = seq(0, 7, by = 1),
                     expand = c(0, 0.5)) +
  scale_fill_viridis_d(begin = 0.4, end = 0.7, labels = virus_sample_labels) +
  scale_color_viridis_d(begin = 0.4, end = 0.7, labels = virus_sample_labels) #-> plot_trans_pfu


plot_trans <- plot_trans_pfu / plot_trans_rna / plot_trans_ratio + 
  plot_annotation(tag_levels = 'a')

# ragg::agg_tiff(filename = "Figure_3_transmisison_wilcox_compare.tiff",
#                width = 5, height = 7, units = 'in', res = 600,
#                scaling = 0.9, compression = "lzw")
# plot(plot_trans)
# invisible(dev.off())

########################################################################################

### FIGURE 4 - Correlation plots

#scales::show_col(viridis::viridis(n = 25, option = 'magma'))

## NW v NIOSH

## AUC PFU by transmissible
p_AUC_PFU_stat <- data_long %>% 
  select(Sample, Variable, Value, trans_3cat) %>%
  distinct() %>%
  filter(Sample != "SPOT", 
         Variable == "AUC_PFU") %>% 
  ggplot(aes(x = trans_3cat, y = Value, fill = trans_3cat, color = trans_3cat)) +
  geom_boxplot(alpha = 0.4) +
  geom_point() +
  geom_boxplot(alpha = 0.4) +
  facet_wrap(~ Sample, scales = "free_y", 
             labeller = as_labeller(c(NW = "Nasal Wash", NIOSH = "Air / BC 251", SPOT = "Air / SPOT"))) + 
  ## accurate Dunn test p-values
  ggpubr::geom_pwc(method = 'dunn_test', label = 'p.adj.signif', hide.ns = TRUE) +
  ## overall Kruskal-Wallis stat
  # ggpubr::stat_kruskal_test(label = "p.format", label.y.npc = "bottom", 
  #                           label.x.npc = "center", hjust = 0.5,
  #                           size = 6, fontface = "bold") +
  ## not consistent with Dunn, Wilcox p-values
  # ggpubr::stat_compare_means(comparisons = list(c("High-transmissible", "Low-transmissible"),
  #                                               c("Non-transmissible", "Low-transmissible"),
  #                                               c("High-transmissible", "Non-transmissible")),
  #                            size = 6, step.increase = 0.5, label = "p.signif", method = "wilcox.test") +
  theme_void() +
  labs(y = expression("log"[10]*" Value")) +
  ylim(NA, max(data_long$Value) + 0.6) +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        strip.text = element_text(size = 15),
        #panel.background = element_rect(fill = 'white', color = 'white'),
        plot.background = element_rect(color = "black", size = 1, fill = 'white')) +
  scale_fill_viridis_d(begin = 0.2, end = 0.75, option = 'magma') +
  scale_color_viridis_d(begin = 0.2, end = 0.75, option = 'magma')

norm_data %>%
  group_by(Virus, ferret) %>%
  mutate(Sample2 = case_when(Sample == 'NW' ~ 'NW', 
                             Sample == 'NIOSH' ~ 'Air', 
                             Sample == 'SPOT' ~ 'Air'),
         occurrence = row_number()) %>%
  ungroup() %>%
  filter(Sample != 'SPOT') %>%
  pivot_wider(names_from = Sample2, values_from = c(AUC_PFU, AUC_RNA),
              id_cols = c(Virus, day, ferret, trans_3cat)) %>%
  unnest(cols = everything()) %>% 
  distinct() %>%
  #subset(!(Virus %in% c("CA147", "CO137"))) %>%
  ggplot(aes(x = AUC_PFU_NW, y = AUC_PFU_Air, color = trans_3cat)) + 
  geom_smooth(method = 'lm', se = TRUE, color = "darkorchid4", 
              alpha = 0.2, linetype = 'dashed') +
  geom_point(size = 6, alpha = 0.9) +
  ggrepel::geom_text_repel(aes(label = Virus), size = 5, 
                           data = . %>% group_by(AUC_PFU_NW, AUC_PFU_Air) %>% slice(1)) +
  ggpubr::stat_cor(aes(x = AUC_PFU_NW, y = AUC_PFU_Air), method = "pearson", 
                   label.x.npc = "left", label.y.npc = 'top', size = 5) + 
  ggpubr::stat_cor(aes(x = AUC_PFU_NW, y = AUC_PFU_Air), method = "pearson", 
                   label.y.npc = 0.85, label.x.npc = 'left', size = 5, color = 'black') +
  #ggpp::stat_group_counts(label.x = 'right', label.y = 'top', vstep = 0.02) +
  #facet_grid(~ Virus, labeller = virus_sample_labels) +
  labs(title = 'a',
       x = "Nasal Wash PFU Area Under the Curve of Days 1-3",
       y = "Airborne PFU Area Under the Curve of Days 1-3") +
  theme_bw() +
  theme(legend.position = 'bottom',
        axis.text = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 16, face = "bold"),
        legend.text = element_text(size = 14, face = "bold"),
        legend.title = element_blank()) +
  scale_color_viridis_d(begin = 0.2, end = 0.75, option = 'magma') +
  annotation_custom(ggplotGrob(p_AUC_PFU_stat), 
                    xmin = 7, xmax = Inf, ymin = -Inf, ymax = 0.95) #-> plot_cor_pfu

# ragg::agg_tiff(filename = "Figure_correlation_NWvNIOSH_AUC_PFU.tiff",
#                width = 9, height = 11, units = 'in', res = 600, 
#                scaling = 1, compression = "lzw")
# plot(plot_cor_pfu)
# invisible(dev.off())

###

## AUC RNA by transmissible
p_AUC_RNA_stat <- data_long %>% 
  select(Sample, Variable, Value, trans_3cat) %>%
  distinct() %>%
  filter(Sample != "SPOT", 
         Variable == "AUC_RNA") %>%
  ggplot(aes(x = trans_3cat, y = Value, fill = trans_3cat, color = trans_3cat)) +
  geom_boxplot(alpha = 0.4) +
  geom_point() +
  geom_boxplot(alpha = 0.4) +
  facet_wrap(~ Sample, scales = "free_y", 
             labeller = as_labeller(c(NW = "Nasal Wash", NIOSH = "Air / BC 251", SPOT = "Air / SPOT"))) + 
  ## accurate Dunn test p-values
  ggpubr::geom_pwc(method = 'dunn_test', label = 'p.adj.signif', hide.ns = TRUE) +
  ## overall Kruskal-Wallis stat
  # ggpubr::stat_kruskal_test(label = "p.format", label.y.npc = "bottom", 
  #                           label.x.npc = "center", hjust = 0.5,
  #                           size = 6, fontface = "bold") +
  ## not consistent with Dunn, Wilcox p-values
  # ggpubr::stat_compare_means(comparisons = list(c("High-transmissible", "Low-transmissible"),
  #                                               c("Non-transmissible", "Low-transmissible"),
  #                                               c("High-transmissible", "Non-transmissible")), 
  #                            size = 6, step.increase = 0.16, label = "p.signif", method = "wilcox.test") +
  theme_void() +
  labs(y = expression("log"[10]*" Value")) +
  ylim(NA, max(data_long$Value) + 0.75) +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        strip.text = element_text(size = 15),
        #panel.background = element_rect(fill = 'white', color = 'white'),
        plot.background = element_rect(color = "black", size = 1, fill = 'white')) +
  scale_fill_viridis_d(begin = 0.2, end = 0.75, option = 'magma') +
  scale_color_viridis_d(begin = 0.2, end = 0.75, option = 'magma')


norm_data %>%
  group_by(Virus, ferret) %>%
  mutate(Sample2 = case_when(Sample == 'NW' ~ 'NW', 
                             Sample == 'NIOSH' ~ 'Air', 
                             Sample == 'SPOT' ~ 'Air'),
         occurrence = row_number()) %>%
  ungroup() %>%
  filter(Sample != 'SPOT') %>%
  pivot_wider(names_from = Sample2, values_from = c(AUC_PFU, AUC_RNA),
              id_cols = c(Virus, day, ferret, trans_3cat)) %>%
  unnest(cols = everything()) %>% 
  distinct() %>% 
  #subset(!(Virus %in% c("CA147", "CO137", "MI90"))) %>%
  ggplot(aes(x = AUC_RNA_NW, y = AUC_RNA_Air, color = trans_3cat)) + 
  geom_smooth(method = 'lm', se = TRUE, color = "darkorchid4", 
              alpha = 0.2, linetype = 'dashed') +
  geom_point(size = 6, alpha = 0.9) +
  ggrepel::geom_text_repel(aes(label = Virus), size = 5, 
                           data = . %>% group_by(AUC_RNA_NW, AUC_RNA_Air) %>% slice(1)) +
  ggpubr::stat_cor(aes(x = AUC_RNA_NW, y = AUC_RNA_Air), method = "pearson", 
                   label.x.npc = "left", label.y.npc = 'top', size = 5) + 
  ggpubr::stat_cor(aes(x = AUC_RNA_NW, y = AUC_RNA_Air), method = "pearson", 
                   label.y.npc = 0.85, label.x.npc = 'left', size = 5, color = 'black') +
  #ggpp::stat_group_counts(label.x = 'right', label.y = 'top', vstep = 0.02) +
  #facet_grid(~ Virus, labeller = virus_sample_labels) +
  labs(title = 'b',
       x = "Nasal Wash RNA Area Under the Curve of Days 1-3",
       y = "Airborne RNA Area Under the Curve of Days 1-3") +
  theme_bw() +
  theme(legend.position = 'bottom',
        axis.text = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 16, face = "bold"),
        legend.text = element_text(size = 14, face = "bold"),
        legend.title = element_blank()) +
  scale_color_viridis_d(begin = 0.2, end = 0.8, option = 'magma') +
  annotation_custom(ggplotGrob(p_AUC_RNA_stat), 
                    xmin = 9.7, xmax = Inf, ymin = -Inf, ymax = 4.5) #-> plot_cor_rna

# ragg::agg_tiff(filename = "Figure_correlation_NWvNIOSH_AUC_RNA.tiff",
#                width = 9, height = 11, units = 'in', res = 600, 
#                scaling = 1, compression = "lzw")
# plot(plot_cor_rna)
# invisible(dev.off())

## combine plots
p23 <- plot_cor_pfu + plot_cor_rna #+ plot_annotation(tag_levels = 'A')
# ragg::agg_tiff(filename = "Figure_4_correlation_NWvNIOSH_AUC_PFU-RNA.tiff",
#                width = 12, height = 11, units = 'in', res = 600,
#                scaling = 0.8, compression = "lzw")
# plot(p23)
# invisible(dev.off())

########################################################################################

### FIGURE 5 - GLM Probabilities

data <- norm_data %>% filter(Sample == 'NIOSH') %>%
  mutate(trans_cat = as.factor(trans_cat))

model <- glm(trans_cat ~ AUC_PFU, data = data, family = binomial())
preds <- predict(model, newdata = data, type = "response")
data$pred_AUC_PFU <- preds

model <- glm(trans_cat ~ AUC_RNA, data = data, family = binomial())
preds <- predict(model, newdata = data, type = "response")
data$pred_AUC_RNA <- preds

data %>% select(Virus, AUC_PFU, AUC_RNA, trans, trans_cat, pred_AUC_PFU, pred_AUC_RNA) %>% distinct() %>% View()

###

plot_prob_threshold <- function(data, outcome, predictor, prob_thresholds = c(0.5, 0.75), 
                                n_points = 500, link = "logit", xlabel = NULL) {
  ## create formula dynamically
  formula <- as.formula(paste0(outcome, " ~ ", predictor))
  ## fit logistic regression
  model <- glm(formula, data = data, family = binomial(link = link))
  ## generate prediction grid
  x_vals <- seq(min(data[[predictor]], na.rm = TRUE),
                max(data[[predictor]], na.rm = TRUE),
                length.out = n_points)
  newdata <- data.frame(x = x_vals)
  names(newdata) <- predictor
  ## predict probabilities and standard errors
  preds <- predict(model, newdata = newdata, type = "link", se.fit = TRUE)
  ## transform logit predictions back to probability scale
  newdata$predicted_prob <- plogis(preds$fit)
  newdata$lower_ci <- plogis(preds$fit - 1.96 * preds$se.fit)
  newdata$upper_ci <- plogis(preds$fit + 1.96 * preds$se.fit)
  ## calculate thresholds
  threshold_points <- sapply(prob_thresholds, function(p) {
    index <- which.min(abs(newdata$predicted_prob - p))
    newdata[[predictor]][index]})
  ## plot with confidence interval shading
  p <- ggplot(newdata, aes_string(x = predictor, y = "predicted_prob")) +
    geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), fill = "darkorchid", alpha = 0.1) +
    geom_line(color = "darkorchid4", linewidth = 1.2) +
    scale_x_continuous(breaks = seq(0, 7, by = 1)) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    labs(#title = paste("Predicted Probability of", outcome, "vs", predictor),
      #title = paste("Predicted Probability of Transmission vs", predictor),
      #x = predictor, 
      x = paste("Airborne", xlabel, "Area Under the Curve of Days 1-3"),
      y = "Probability of Transmission (%)") +
    theme_minimal() +
    theme(axis.text.y = element_text(face = "bold", size = 12),
          #axis.title.y = element_blank(),
          #axis.title.y = element_text(face = "bold", size = 14),
          axis.text.x = element_text(face = "bold", size = 12),
          axis.title.x = element_text(face = "bold", size = 13))
  ## add threshold lines and annotations
  ## use different colors for each threshold. #colors must = #thresholds
  colors <- c("red3", "blue3")
  for (i in seq_along(prob_thresholds)) {
    p <- p +
      geom_hline(yintercept = prob_thresholds[i], linetype = "dotted", color = "gray50") +
      geom_vline(xintercept = threshold_points[i], linetype = "dashed", linewidth = 1, 
                 color = colors[i], alpha = 0.5) +
      annotate("text",
               x = threshold_points[i], y = prob_thresholds[i] - 0.02,
               label = paste0(predictor, " ≈ ", round(threshold_points[i], 3)),
               hjust = -0.1, color = colors[i])}
  ## hard code the colors as red
  # for (i in seq_along(prob_thresholds)) {
  #   p <- p +
  #     geom_hline(yintercept = prob_thresholds[i], linetype = "dotted", color = "gray50") +
  #     geom_vline(xintercept = threshold_points[i], linetype = "dashed", linewidth = 1, color = "red", alpha = 0.5) +
  #     annotate("text",
  #              x = threshold_points[i], y = prob_thresholds[i] - 0.02,
  #              label = paste0(predictor, " ≈ ", round(threshold_points[i], 3)),
  #              hjust = -0.1, color = "red3")}
  return(p)}


#plot_prob_threshold(data = data, outcome = "trans", predictor = "PFU")
plot_prob_threshold(data = data, outcome = "trans_cat", predictor = "PFU")
#plot_prob_threshold(data = data, outcome = "trans", predictor = "AUC_PFU")
plot_prob_threshold(data = data, outcome = "trans_cat", predictor = "AUC_PFU")
#plot_prob_threshold(data = data, outcome = "trans", predictor = "RNA")
plot_prob_threshold(data = data, outcome = "trans_cat", predictor = "RNA")
#plot_prob_threshold(data = data, outcome = "trans", predictor = "AUC_RNA")
plot_prob_threshold(data = data, outcome = "trans_cat", predictor = "AUC_RNA")

plot_prob_auc_pfu <- plot_prob_threshold(data = data, outcome = "trans_cat", 
                                         predictor = "AUC_PFU", xlabel = 'PFU')
plot_prob_auc_rna <- plot_prob_threshold(data = data, outcome = "trans_cat", 
                                         predictor = "AUC_RNA", xlabel = 'RNA')

## import the Excel Table > MS Paint PNG file
image <- figpatch::fig("Source_Data/Figure_5C_table-heatmap.png")

## patchwork
plot_auc_probs <- ((plot_prob_auc_pfu / plot_prob_auc_rna) | image) + plot_annotation(tag_levels = 'a')

# ragg::agg_tiff(filename = "Figure_5_AUC_probabilities.tiff",
#                width = 8, height = 6, units = 'in', res = 600,
#                scaling = 1, compression = "lzw")
# plot(plot_auc_probs)
# invisible(dev.off())

########################################################################################
########################################################################################
### SUPPLEMENTARY FIGURES ###
########################################################################################
########################################################################################

### SUPPLEMENTARY FIGURE 1

## RNA line plots only
data_stats %>% 
  filter(Sample != 'NW') %>%
  ggplot(aes(x = day, color = Sample, fill = Sample)) +
  geom_ribbon(aes(group = Sample, ymin = mr - ser, ymax = mr + ser), 
              alpha = 0.2) +
  geom_point(aes(y = mr), size = 2, alpha = 1) +
  geom_line(aes(y = mr, group = Sample), size = 0.8, alpha = 1) +
  scale_fill_viridis_d(begin = 0.4, end = 0.8, labels = virus_sample_labels) +
  scale_color_viridis_d(begin = 0.4, end = 0.8, labels = virus_sample_labels) +
  facet_grid(~ Virus, labeller = virus_sample_labels) +
  theme_minimal() +
  theme(legend.position = 'bottom') +
  labs(x = 'Day Post-Inocluation',
       y = expression(log[10]~paste("RNA"))) #-> plot_air_lines_rna

## PFU line plots only
data_stats %>% 
  filter(Sample != 'NW') %>%
  ggplot(aes(x = day, color = Sample, fill = Sample)) +
  geom_ribbon(aes(group = Sample, ymin = mp - sep, ymax = mp + sep), 
              alpha = 0.2) +
  geom_point(aes(y = mp), size = 2, alpha = 1) +
  geom_line(aes(y = mp, group = Sample), size = 0.8, alpha = 1) +
  scale_fill_viridis_d(begin = 0.4, end = 0.8, labels = virus_sample_labels) +
  scale_color_viridis_d(begin = 0.4, end = 0.8, labels = virus_sample_labels) +
  facet_grid(~ Virus, labeller = virus_sample_labels) +
  theme_minimal() +
  theme(legend.position = 'none') +
  labs(x = 'Day Post-Inocluation',
       y = expression(log[10]~paste("PFU"))) #-> plot_air_lines_pfu


## combine plots
plot_lines <- plot_air_lines_pfu / plot_air_lines_rna + plot_annotation(tag_levels = 'a')

# ragg::agg_tiff(filename = "Figure_S1_air_lines_PFU-RNA.tiff",
#                width = 8, height = 6, units = 'in', res = 600,
#                scaling = 1, compression = "lzw")
# plot(plot_lines)
# invisible(dev.off())

########################################################################################

### SUPPLEMENTARY FIGURE 2

## NW v SPOT

## AUC PFU by transmissible
p_AUC_PFU_stat <- data_long %>% 
  select(Sample, Variable, Value, trans_3cat) %>%
  distinct() %>%
  filter(Sample != "NIOSH",
         Variable == "AUC_PFU") %>% 
  ggplot(aes(x = trans_3cat, y = Value, fill = trans_3cat, color = trans_3cat)) +
  geom_boxplot(alpha = 0.4) +
  geom_point() +
  geom_boxplot(alpha = 0.4) +
  facet_wrap(~ Sample, scales = "free_y", 
             labeller = as_labeller(c(NW = "Nasal Wash", NIOSH = "Air / BC 251", SPOT = "Air / SPOT"))) + 
  ## accurate Dunn test p-values
  ggpubr::geom_pwc(method = 'dunn_test', label = 'p.format', step.increase = 0.4) +
  ## overall Kruskal-Wallis stat
  # ggpubr::stat_kruskal_test(label = "p.format", label.y.npc = "bottom", 
  #                           label.x.npc = "center", hjust = 0.5,
  #                           size = 6, fontface = "bold") +
  ## not consistent with Dunn, Wilcox p-values
  # ggpubr::stat_compare_means(comparisons = list(c("High-transmissible", "Low-transmissible"),
  #                                               c("Non-transmissible", "Low-transmissible"),
  #                                               c("High-transmissible", "Non-transmissible")),
  #                            size = 6, step.increase = 0.5, label = "p.signif", method = "wilcox.test") +
  theme_void() +
  labs(y = expression("log"[10]*" Value")) +
  ylim(NA, max(data_long$Value) + 0.6) +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        strip.text = element_text(size = 15),
        #panel.background = element_rect(fill = 'white', color = 'white'),
        plot.background = element_rect(color = "black", size = 1, fill = 'white')) +
  scale_fill_viridis_d(begin = 0.2, end = 0.75, option = 'magma') +
  scale_color_viridis_d(begin = 0.2, end = 0.75, option = 'magma')

norm_data %>%
  group_by(Virus, ferret) %>%
  mutate(Sample2 = case_when(Sample == 'NW' ~ 'NW', 
                             Sample == 'NIOSH' ~ 'Air', 
                             Sample == 'SPOT' ~ 'Air'),
         occurrence = row_number()) %>%
  ungroup() %>%
  filter(Sample != 'NIOSH') %>%
  pivot_wider(names_from = Sample2, values_from = c(AUC_PFU, AUC_RNA),
              id_cols = c(Virus, day, ferret, trans_3cat)) %>%
  unnest(cols = everything()) %>% 
  distinct() %>%
  #subset(!(Virus %in% c("CA147", "CO137"))) %>%
  ggplot(aes(x = AUC_PFU_NW, y = AUC_PFU_Air, color = trans_3cat)) + 
  geom_smooth(method = 'lm', se = TRUE, color = "darkorchid4", 
              alpha = 0.2, linetype = 'dashed') +
  geom_point(size = 6, alpha = 0.9) +
  ggrepel::geom_text_repel(aes(label = Virus), size = 5, 
                           data = . %>% group_by(AUC_PFU_NW, AUC_PFU_Air) %>% slice(1)) +
  ggpubr::stat_cor(aes(x = AUC_PFU_NW, y = AUC_PFU_Air), method = "pearson", 
                   label.x.npc = "left", label.y.npc = 'top', size = 5) + 
  ggpubr::stat_cor(aes(x = AUC_PFU_NW, y = AUC_PFU_Air), method = "pearson", 
                   label.y.npc = 0.85, label.x.npc = 'left', size = 5, color = 'black') +
  #ggpp::stat_group_counts(label.x = 'right', label.y = 'top', vstep = 0.02) +
  #facet_grid(~ Virus, labeller = virus_sample_labels) +
  labs(title = 'a', 
       x = "Nasal Wash PFU Area Under the Curve of Days 1-3",
       y = "Airborne PFU Area Under the Curve of Days 1-3") +
  theme_bw() +
  theme(legend.position = 'bottom',
        axis.text = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 16, face = "bold"),
        legend.text = element_text(size = 14, face = "bold"),
        legend.title = element_blank()) +
  scale_color_viridis_d(begin = 0.2, end = 0.75, option = 'magma') +
  annotation_custom(ggplotGrob(p_AUC_PFU_stat), 
                    xmin = 7, xmax = Inf, ymin = -Inf, ymax = 0.45) #-> plot_cor_pfu_spot

# ragg::agg_tiff(filename = "Figure_correlation_NWvNIOSH_AUC_PFU.tiff",
#                width = 9, height = 11, units = 'in', res = 600, 
#                scaling = 1, compression = "lzw")
# plot(plot_cor_pfu)
# invisible(dev.off())

###

## AUC RNA by transmissible
p_AUC_RNA_stat <- data_long %>% 
  select(Sample, Variable, Value, trans_3cat) %>%
  distinct() %>%
  filter(Sample != "NIOSH", 
         Variable == "AUC_RNA") %>%
  ggplot(aes(x = trans_3cat, y = Value, fill = trans_3cat, color = trans_3cat)) +
  geom_boxplot(alpha = 0.4) +
  geom_point() +
  geom_boxplot(alpha = 0.4) +
  facet_wrap(~ Sample, scales = "free_y", 
             labeller = as_labeller(c(NW = "Nasal Wash", NIOSH = "Air / BC 251", SPOT = "Air / SPOT"))) + 
  ## accurate Dunn test p-values
  ggpubr::geom_pwc(method = 'dunn_test', label = 'p.format', step.increase = 0.2) +
  ## overall Kruskal-Wallis stat
  # ggpubr::stat_kruskal_test(label = "p.format", label.y.npc = "bottom", 
  #                           label.x.npc = "center", hjust = 0.5,
  #                           size = 6, fontface = "bold") +
  ## not consistent with Dunn, Wilcox p-values
  # ggpubr::stat_compare_means(comparisons = list(c("High-transmissible", "Low-transmissible"),
  #                                               c("Non-transmissible", "Low-transmissible"),
  #                                               c("High-transmissible", "Non-transmissible")), 
  #                            size = 6, step.increase = 0.16, label = "p.signif", method = "wilcox.test") +
  theme_void() +
  labs(y = expression("log"[10]*" Value")) +
  ylim(NA, max(data_long$Value) + 0.75) +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        strip.text = element_text(size = 15),
        #panel.background = element_rect(fill = 'white', color = 'white'),
        plot.background = element_rect(color = "black", size = 1, fill = 'white')) +
  scale_fill_viridis_d(begin = 0.2, end = 0.75, option = 'magma') +
  scale_color_viridis_d(begin = 0.2, end = 0.75, option = 'magma')


norm_data %>%
  group_by(Virus, ferret) %>%
  mutate(Sample2 = case_when(Sample == 'NW' ~ 'NW', 
                             Sample == 'NIOSH' ~ 'Air', 
                             Sample == 'SPOT' ~ 'Air'),
         occurrence = row_number()) %>%
  ungroup() %>%
  filter(Sample != 'NIOSH') %>%
  pivot_wider(names_from = Sample2, values_from = c(AUC_PFU, AUC_RNA),
              id_cols = c(Virus, day, ferret, trans_3cat)) %>%
  unnest(cols = everything()) %>% 
  distinct() %>% 
  #subset(!(Virus %in% c("CA147", "CO137", "MI90"))) %>%
  ggplot(aes(x = AUC_RNA_NW, y = AUC_RNA_Air, color = trans_3cat)) + 
  geom_smooth(method = 'lm', se = TRUE, color = "darkorchid4", 
              alpha = 0.2, linetype = 'dashed') +
  geom_point(size = 6, alpha = 0.9) +
  ggrepel::geom_text_repel(aes(label = Virus), size = 5, 
                           data = . %>% group_by(AUC_RNA_NW, AUC_RNA_Air) %>% slice(1)) +
  ggpubr::stat_cor(aes(x = AUC_RNA_NW, y = AUC_RNA_Air), method = "pearson", 
                   label.x.npc = "left", label.y.npc = 'top', size = 5) + 
  ggpubr::stat_cor(aes(x = AUC_RNA_NW, y = AUC_RNA_Air), method = "pearson", 
                   label.y.npc = 0.85, label.x.npc = 'left', size = 5, color = 'black') +
  #ggpp::stat_group_counts(label.x = 'right', label.y = 'top', vstep = 0.02) +
  #facet_grid(~ Virus, labeller = virus_sample_labels) +
  labs(title = 'b',
       x = "Nasal Wash RNA Area Under the Curve of Days 1-3",
       y = "Airborne RNA Area Under the Curve of Days 1-3") +
  theme_bw() +
  theme(legend.position = 'bottom',
        axis.text = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 16, face = "bold"),
        legend.text = element_text(size = 14, face = "bold"),
        legend.title = element_blank()) +
  scale_color_viridis_d(begin = 0.2, end = 0.8, option = 'magma') +
  annotation_custom(ggplotGrob(p_AUC_RNA_stat), 
                    xmin = 9.5, xmax = Inf, ymin = -Inf, ymax = 2.1) #-> plot_cor_rna_spot


## combine plots
p45 <- plot_cor_pfu_spot + plot_cor_rna_spot
# ragg::agg_tiff(filename = "Figure_S2_correlation_NWvSPOT_AUC_PFU-RNA.tiff",
#                width = 12, height = 11, units = 'in', res = 600,
#                scaling = 0.8, compression = "lzw")
# plot(p45)
# invisible(dev.off())

########################################################################################

### SUPPLEMENTARY FIGURE 3

### PFU/RNA by day

## NIOSH RNA
norm_data %>%
  filter(day != 'd5') %>%
  group_by(Virus, ferret) %>%
  mutate(Sample2 = case_when(Sample == 'NW' ~ 'NW', 
                             Sample == 'NIOSH' ~ 'Air', 
                             Sample == 'SPOT' ~ 'Air'),
         occurrence = row_number()) %>%
  ungroup() %>%
  filter(Sample != 'SPOT') %>%
  pivot_wider(names_from = Sample2, values_from = c(PFU, RNA),
              id_cols = c(Virus, day, ferret, trans_3cat)) %>%
  unnest(cols = everything()) %>% 
  distinct() %>% 
  ggplot(aes(x = RNA_NW, y = RNA_Air, color = trans_3cat)) +
  geom_smooth(method = 'lm', se = TRUE, color = "darkorchid4", 
              alpha = 0.2, linetype = 'dashed') +
  geom_point(size = 5, alpha = 0.8) +  
  # ggpubr::stat_cor(method = "pearson", 
  #                  label.x.npc = "center", label.y.npc = 'bottom') + 
  ggpubr::stat_cor(method = "pearson", size = 5,
                   label.x.npc = 'left', label.y.npc = 'top', color = 'black') +
  #ggpp::stat_group_counts(label.x = 'left', label.y = 'top', vstep = 0.02) +
  scale_fill_viridis_d(begin = 0.2, end = 0.8, option = 'magma', labels = virus_sample_labels) +
  scale_color_viridis_d(begin = 0.2, end = 0.8, option = 'magma', labels = virus_sample_labels) +
  scale_y_continuous(breaks = seq(0, 11, by = 1)) +
  labs(x = expression("log"[10]*" Nasal Wash RNA"),
       y = expression("log"[10]*" Air / BC 251 RNA")) +
  facet_grid(~ day, scales = 'free', labeller = virus_sample_labels) +
  theme_minimal() +
  theme(legend.title = element_blank(),
        legend.position = 'none', 
        axis.text = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 16, face = "bold"),
        legend.text = element_text(size = 14, face = "bold"),
        strip.text = element_text(size = 16, face = "bold"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  guides(color = guide_legend(nrow = 1)) #-> plot_day_niosh_rna

## NIOSH PFU
norm_data %>%
  filter(day != 'd5') %>%
  group_by(Virus, ferret) %>%
  mutate(Sample2 = case_when(Sample == 'NW' ~ 'NW', 
                             Sample == 'NIOSH' ~ 'Air', 
                             Sample == 'SPOT' ~ 'Air'),
         occurrence = row_number()) %>%
  ungroup() %>%
  filter(Sample != 'SPOT') %>%
  pivot_wider(names_from = Sample2, values_from = c(PFU, RNA),
              id_cols = c(Virus, day, ferret, trans_3cat)) %>%
  unnest(cols = everything()) %>% 
  distinct() %>% 
  ggplot(aes(x = PFU_NW, y = PFU_Air, color = trans_3cat)) +
  geom_smooth(method = 'lm', se = TRUE, color = "darkorchid4", 
              alpha = 0.2, linetype = 'dashed') +
  geom_point(size = 5, alpha = 0.8) +  
  # ggpubr::stat_cor(method = "pearson", 
  #                  label.x.npc = "center", label.y.npc = 'bottom') + 
  ggpubr::stat_cor(method = "pearson", size = 5,
                   label.x.npc = 'left', label.y.npc = 'top', color = 'black') +
  #ggpp::stat_group_counts(label.x = 'left', label.y = 'top', vstep = 0.02) +
  scale_fill_viridis_d(begin = 0.2, end = 0.8, option = 'magma', labels = virus_sample_labels) +
  scale_color_viridis_d(begin = 0.2, end = 0.8, option = 'magma', labels = virus_sample_labels) +
  scale_y_continuous(breaks = seq(0, 11, by = 1)) +
  labs(x = expression("log"[10]*" Nasal Wash PFU"),
       y = expression("log"[10]*" Air / BC 251 PFU")) +
  facet_grid(~ day, scales = 'free', labeller = virus_sample_labels) +
  theme_minimal() +
  theme(legend.title = element_blank(),
        legend.position = 'none', 
        axis.text = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 16, face = "bold"),
        legend.text = element_text(size = 14, face = "bold"),
        strip.text = element_text(size = 16, face = "bold"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  guides(color = guide_legend(nrow = 1)) #-> plot_day_niosh_pfu


## SPOT RNA
norm_data %>%
  filter(day != 'd5') %>%
  group_by(Virus, ferret) %>%
  mutate(Sample2 = case_when(Sample == 'NW' ~ 'NW', 
                             Sample == 'NIOSH' ~ 'Air', 
                             Sample == 'SPOT' ~ 'Air'),
         occurrence = row_number()) %>%
  ungroup() %>%
  filter(Sample != 'NIOSH') %>%
  pivot_wider(names_from = Sample2, values_from = c(PFU, RNA),
              id_cols = c(Virus, day, ferret, trans_3cat)) %>%
  unnest(cols = everything()) %>% 
  distinct() %>% 
  ggplot(aes(x = RNA_NW, y = RNA_Air, color = trans_3cat)) +
  geom_smooth(method = 'lm', se = TRUE, color = "darkorchid4", 
              alpha = 0.2, linetype = 'dashed') +
  geom_point(size = 5, alpha = 0.8) +  
  # ggpubr::stat_cor(method = "pearson", 
  #                  label.x.npc = "center", label.y.npc = 'bottom') + 
  ggpubr::stat_cor(method = "pearson", size = 5,
                   label.x.npc = 'left', label.y.npc = 'top', color = 'black') +
  #ggpp::stat_group_counts(label.x = 'left', label.y = 'top', vstep = 0.02) +
  scale_fill_viridis_d(begin = 0.2, end = 0.8, option = 'magma', labels = virus_sample_labels) +
  scale_color_viridis_d(begin = 0.2, end = 0.8, option = 'magma', labels = virus_sample_labels) +
  scale_y_continuous(breaks = seq(0, 11, by = 1)) +
  labs(x = expression("log"[10]*" Nasal Wash RNA"),
       y = expression("log"[10]*" Air / SPOT RNA")) +
  facet_grid(~ day, scales = 'free', labeller = virus_sample_labels) +
  theme_minimal() +
  theme(legend.title = element_blank(),
        legend.position = 'bottom', 
        axis.text = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 16, face = "bold"),
        legend.text = element_text(size = 14, face = "bold"),
        strip.text = element_text(size = 16, face = "bold"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  guides(color = guide_legend(nrow = 1)) #-> plot_day_spot_rna

## SPOT PFU
norm_data %>%
  filter(day != 'd5') %>%
  group_by(Virus, ferret) %>%
  mutate(Sample2 = case_when(Sample == 'NW' ~ 'NW', 
                             Sample == 'NIOSH' ~ 'Air', 
                             Sample == 'SPOT' ~ 'Air'),
         occurrence = row_number()) %>%
  ungroup() %>%
  filter(Sample != 'NIOSH') %>%
  pivot_wider(names_from = Sample2, values_from = c(PFU, RNA),
              id_cols = c(Virus, day, ferret, trans_3cat)) %>%
  unnest(cols = everything()) %>% 
  distinct() %>% 
  ggplot(aes(x = PFU_NW, y = PFU_Air, color = trans_3cat)) +
  geom_smooth(method = 'lm', se = TRUE, color = "darkorchid4", 
              alpha = 0.2, linetype = 'dashed') +
  geom_point(size = 5, alpha = 0.8) +  
  # ggpubr::stat_cor(method = "pearson", 
  #                  label.x.npc = "center", label.y.npc = 'bottom') + 
  ggpubr::stat_cor(method = "pearson", size = 5,
                   label.x.npc = 'left', label.y.npc = 'top', color = 'black') +
  #ggpp::stat_group_counts(label.x = 'left', label.y = 'top', vstep = 0.02) +
  scale_fill_viridis_d(begin = 0.2, end = 0.8, option = 'magma', labels = virus_sample_labels) +
  scale_color_viridis_d(begin = 0.2, end = 0.8, option = 'magma', labels = virus_sample_labels) +
  scale_y_continuous(breaks = seq(0, 11, by = 1)) +
  labs(x = expression("log"[10]*" Nasal Wash PFU"),
       y = expression("log"[10]*" Air / SPOT PFU")) +
  facet_grid(~ day, scales = 'free', labeller = virus_sample_labels) +
  theme_minimal() +
  theme(legend.title = element_blank(),
        legend.position = 'none', 
        axis.text = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 16, face = "bold"),
        legend.text = element_text(size = 14, face = "bold"),
        strip.text = element_text(size = 16, face = "bold"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  guides(color = guide_legend(nrow = 1)) #-> plot_day_spot_pfu

## combine plots
plots_day <- plot_day_niosh_pfu / plot_day_spot_pfu / plot_day_niosh_rna / plot_day_spot_rna

# ragg::agg_tiff(filename = "Figure_S3_correlation_day_NIOSHvSPOT_PFU-RNA.tiff",
#                width = 10, height = 12, units = 'in', res = 600,
#                scaling = 0.8, compression = "lzw")
# plot(plots_day)
# invisible(dev.off())

########################################################################################
########################################################################################
### STATISTICS ###
########################################################################################
########################################################################################

## check normality and homogeneity of variance assumptions
## RNA & PFU & AUC
norm_data %>% 
  filter(Sample != 'NW') %>% 
  pivot_longer(cols = c(RNA, PFU, AUC_RNA, AUC_PFU), 
               names_to = "Variable", 
               values_to = "Value") %>% 
  ## Kurskal-Wallis/Wilcox for all data aggregated
  #filter(Variable == "PFU") %>%           ## Kurskal-Wallis/Wilcox
  #filter(Variable == "RNA") %>%           ## Kurskal-Wallis/Wilcox
  perform_assumption_checks(group_vars = c("day", "Sample"), "Value") %>% View()


norm_data %>% 
  pivot_longer(cols = c(RNA, PFU, AUC_RNA, AUC_PFU), 
               names_to = "Variable", 
               values_to = "Value") %>% 
  ## Kurskal-Wallis/Wilcox for all data aggregated
  #filter(Variable == "PFU") %>%           ## Kurskal-Wallis/Wilcox
  #filter(Variable == "RNA") %>%           ## Kurskal-Wallis/Wilcox
  perform_assumption_checks(group_vars = c("day", "Sample", "trans_cat"), "Value") %>% View()

########################################################################################

## stats ratio between Sample
norm_data %>%
  select(Sample, ratio) %>%
  filter(ratio > 0) %>%
  distinct() %>%
  #group_by(Sample) %>%
  #kruskal.test(AUC_RNA ~ trans_cat, data = .)
  rstatix::dunn_test(ratio ~ Sample, data = ., p.adjust.method = "holm") %>%
  View()

########################################################################################

## stats between transmissible and non-transmissible viruses
norm_data %>%
  select(Sample, AUC_PFU, trans_cat) %>%
  distinct() %>%
  group_by(Sample) %>%
  #kruskal.test(AUC_PFU ~ trans_cat, data = .)
  rstatix::dunn_test(AUC_PFU ~ trans_cat, data = ., p.adjust.method = "holm") %>%
  View()

norm_data %>%
  select(Sample, AUC_RNA, trans_cat) %>%
  distinct() %>%
  group_by(Sample) %>%
  #kruskal.test(AUC_RNA ~ trans_cat, data = .)
  rstatix::dunn_test(AUC_RNA ~ trans_cat, data = ., p.adjust.method = "holm") %>%
  View()

norm_data %>%
  select(Sample, PFU, trans_cat) %>%
  distinct() %>%
  group_by(Sample) %>%
  #kruskal.test(AUC_PFU ~ trans_cat, data = .)
  rstatix::dunn_test(PFU ~ trans_cat, data = ., p.adjust.method = "holm") %>%
  View()

norm_data %>%
  select(Sample, RNA, trans_cat) %>%
  distinct() %>%
  group_by(Sample) %>%
  #kruskal.test(AUC_RNA ~ trans_cat, data = .)
  rstatix::dunn_test(RNA ~ trans_cat, data = ., p.adjust.method = "holm") %>%
  View()

norm_data %>%
  select(Sample, ratio, trans_cat) %>%
  distinct() %>%
  group_by(Sample) %>%
  #kruskal.test(AUC_RNA ~ trans_cat, data = .)
  rstatix::dunn_test(ratio ~ trans_cat, data = ., p.adjust.method = "holm") %>%
  View()

########################################################################################

## stats between high-transmissible, low-transmissible, non-transmissible viruses
## Supplementary Table 4

norm_data %>%
  select(Sample, AUC_PFU, trans_3cat) %>%
  distinct() %>%
  group_by(Sample) %>%
  #kruskal.test(AUC_PFU ~ trans_cat, data = .)
  rstatix::dunn_test(AUC_PFU ~ trans_3cat, data = ., p.adjust.method = "holm") %>%
  View()

norm_data %>%
  select(Sample, AUC_RNA, trans_3cat) %>%
  distinct() %>%
  group_by(Sample) %>%
  #kruskal.test(AUC_RNA ~ trans_cat, data = .)
  rstatix::dunn_test(AUC_RNA ~ trans_3cat, data = ., p.adjust.method = "holm") %>%
  View()

norm_data %>%
  select(Sample, PFU, trans_3cat) %>%
  distinct() %>%
  group_by(Sample) %>%
  #kruskal.test(AUC_PFU ~ trans_cat, data = .)
  rstatix::dunn_test(PFU ~ trans_3cat, data = ., p.adjust.method = "holm") %>%
  View()

norm_data %>%
  select(Sample, RNA, trans_3cat) %>%
  distinct() %>%
  group_by(Sample) %>%
  #kruskal.test(AUC_RNA ~ trans_cat, data = .)
  rstatix::dunn_test(RNA ~ trans_3cat, data = ., p.adjust.method = "holm") %>%
  View()

norm_data %>%
  select(Sample, ratio, trans_3cat) %>%
  distinct() %>%
  group_by(Sample) %>%
  #kruskal.test(AUC_RNA ~ trans_cat, data = .)
  rstatix::dunn_test(ratio ~ trans_3cat, data = ., p.adjust.method = "holm") %>%
  View()

########################################################################################

## stats between clade D1.1 and B3.13, all viruses
norm_data %>%
  select(Sample, AUC_PFU, clade) %>%
  filter(clade %in% c('D1.1', 'B3.13')) %>%
  #filter(Sample != 'NW') %>%
  distinct() %>%
  group_by(Sample) %>%
  #kruskal.test(AUC_PFU ~ trans_cat, data = .)
  rstatix::dunn_test(AUC_PFU ~ clade, data = ., p.adjust.method = "holm") %>%
  View()

norm_data %>%
  select(Sample, AUC_RNA, clade) %>%
  filter(clade %in% c('D1.1', 'B3.13')) %>%
  #filter(Sample != 'NW') %>%
  distinct() %>%
  group_by(Sample) %>%
  #kruskal.test(AUC_RNA ~ trans_cat, data = .)
  rstatix::dunn_test(AUC_RNA ~ clade, data = ., p.adjust.method = "holm") %>%
  View()

########################################################################################

## compare B3.13 vs D1.1 virus AUC levels, no MI/90

norm_data %>%
  subset(clade %in% c('D1.1', 'B3.13')) %>% 
  filter(Virus != 'MI/90', Sample == 'NIOSH') %>%
  select(clade, AUC_PFU, AUC_RNA) %>%
  distinct() %>%
  rstatix::wilcox_test(AUC_PFU ~ clade, data = .)

norm_data %>%
  subset(clade %in% c('D1.1', 'B3.13')) %>% 
  filter(Virus != 'MI/90', Sample == 'NIOSH') %>%
  select(clade, AUC_PFU, AUC_RNA) %>%
  distinct() %>%
  rstatix::wilcox_test(AUC_RNA ~ clade, data = .)

norm_data %>%
  subset(clade %in% c('D1.1', 'B3.13')) %>% 
  filter(Virus != 'MI/90', Sample == 'NIOSH') %>%
  select(clade, AUC_PFU, AUC_RNA) %>%
  group_by(clade) %>% 
  summarise(mean_AUC_PFU = mean(AUC_PFU, na.rm = TRUE),
            mean_AUC_RNA = mean(AUC_RNA, na.rm = TRUE)) 

########################################################################################

## Fisher's Exact tests
## Supplementary Table 3
norm_data$PFU_binary <- ifelse(norm_data$PFU > 0, "Detected", "Not Detected")
norm_data$RNA_binary <- ifelse(norm_data$RNA > 0, "Detected", "Not Detected")

table_data_PFU <- table(norm_data$Sample, norm_data$PFU_binary)
table_data_PFU

table_data_RNA <- table(norm_data$Sample, norm_data$RNA_binary)
table_data_RNA

fisher.test(table_data_PFU[c("NIOSH", "SPOT"), ])
## NIOSH samples are about 2 times more likely to have detected PFU compared to SPOT samples

fisher.test(table_data_RNA[c("NIOSH", "SPOT"), ])
## NIOSH samples are about 4.18 times more likely to have detected RNA compared to SPOT samples

########################################################################################

### 7 Oct 2025 revisions
### Repeated Measures Analysis

## prep data
norm_data2 <- norm_data %>%
  group_by(Virus, ferret) %>%
  filter(day != 'd5') %>%
  mutate(Sample2 = case_when(Sample == 'NW' ~ 'NW', 
                             Sample == 'NIOSH' ~ 'Air', 
                             Sample == 'SPOT' ~ 'Air'),
         day = factor(day),
         ## add small offset for 0 values
         PFU  = PFU + 0.001,
         RNA = RNA + 0.001,
         occurrence = row_number()) %>%
  ungroup() %>%
  filter(Sample != 'SPOT') %>%
  pivot_wider(names_from = Sample2, values_from = c(PFU, RNA),
              id_cols = c(Virus, day, ferret, trans_3cat)) %>%
  unnest(cols = everything()) %>% 
  distinct()

## mixed-effects models
m_intercept_p <- lme4::lmer(PFU_Air ~ PFU_NW * day + (1 | ferret),
                            data = norm_data2, REML = FALSE,
                            control = lme4::lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5)))

m_intercept_r <- lme4::lmer(RNA_Air ~ RNA_NW * day + (1 | ferret),
                            data = norm_data2, REML = FALSE,
                            control = lme4::lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5)))

# summary(m_intercept_p)
# ## check singularity - should be FALSE
# lme4::isSingular(m_intercept_p, tol = 1e-4)
# performance::check_model(m_intercept_p)
# broom.mixed::tidy(m_intercept_p, conf.int = TRUE)
# 
# summary(m_intercept_r)
# ## check singularity - should be FALSE
# lme4::isSingular(m_intercept_r, tol = 1e-4)
# performance::check_model(m_intercept_r)
# broom.mixed::tidy(m_intercept_r, conf.int = TRUE)

m_final_p <- update(m_intercept_p, REML = TRUE)
m_final_r <- update(m_intercept_r, REML = TRUE)

summary(m_final_p)
lme4::isSingular(m_final_p, tol = 1e-4)
performance::check_model(m_final_p)
broom.mixed::tidy(m_final_p, conf.int = TRUE)

summary(m_final_r)
lme4::isSingular(m_final_r, tol = 1e-4)
performance::check_model(m_final_r)
broom.mixed::tidy(m_final_r, conf.int = TRUE)

###

## simple slopes
em_p <- emmeans::emtrends(m_final_p, ~ day, var = "PFU_NW")
em_r <- emmeans::emtrends(m_final_r, ~ day, var = "RNA_NW")
summary(em_p)
summary(em_r)
## test whether slopes differ by day (pairwise comparisons)
pairs(em_p)
pairs(em_r)

###

## repeated measures correlation - to control for ferret variance
rmc_p <- rmcorr::rmcorr(participant = ferret, measure1 = PFU_NW, measure2 = PFU_Air, dataset = norm_data2)

rmc_r <- rmcorr::rmcorr(participant = ferret, measure1 = RNA_NW, measure2 = RNA_Air, dataset = norm_data2)

ggplot(norm_data2, aes(x = PFU_NW, y = PFU_Air, color = factor(ferret))) +
  rmcorr::geom_rmc(rmc_p) +
  facet_wrap(~Virus) +
  theme_bw()

ggplot(norm_data2, aes(x = RNA_NW, y = RNA_Air, color = factor(ferret))) +
  rmcorr::geom_rmc(rmc_r) +
  facet_wrap(~Virus) +
  theme_bw()

########################################################################################
########################################################################################
### End of code
########################################################################################
########################################################################################
